# Generated by Django 2.0.7 on 2018-07-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('outside_shape', models.CharField(max_length=45)),
                ('base_type', models.CharField(max_length=45)),
                ('height_over_tube', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('bolt_pattern_long', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('bolt_pattern_wide', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('groove', models.BooleanField(default=False)),
                ('base_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('shoulder_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('unique_feature', models.BooleanField(default=False)),
                ('orientation', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='componente_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ComponentType'),
        ),
        migrations.AddField(
            model_name='component',
            name='connection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConnectionType'),
        ),
    ]
