# Generated by Django 2.0.7 on 2018-07-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='componente_type',
            new_name='component_type',
        ),
    ]
