# Generated by Django 2.0.7 on 2018-07-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180725_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Component')),
            ],
        ),
        migrations.CreateModel(
            name='TubeAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ManyToManyField(through='core.AssemblyComponent', to='core.Component')),
            ],
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='tube_assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TubeAssembly'),
        ),
    ]
