# Generated by Django 2.0.7 on 2018-07-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180725_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField()),
                ('annual_usage', models.IntegerField(default=0)),
                ('min_order_quantity', models.IntegerField(default=0)),
                ('bracket_pricing', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pricequote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier'),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='tube_assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TubeAssembly'),
        ),
    ]
